
language: python

python:

  - "3.6-dev"

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pip install coverage


script:
  - pytest --cov=api/

 after-success:
  - coveralls



