
language: python

python:

  - "3.7.1"

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pip install coveralls


script:
  - pytest --cov=./

after-success:
  - coveralls

