
language: python

python:

  - "3.6-dev"

install:
    - pip install -r requirements.txt
    - pip install pytest 
    - pip install pytest-cov
    - pip install coveralls
    - pip install coveralls-python


script:
  - pytest
  - coverage run --source=my_package setup.py test

 after-success:
   - coveralls



