
language: python

python:

  - "3.6-dev"

install:
    - pip install -r requirements.txt
    - pip install pytest 
    - pip install pytest-cov
    - pip install coveralls
    - pip install python-coveralls

script:
  - pytest --cov=./

 after-success:
  - coveralls



